# Generated by Django 3.2.5 on 2021-07-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
    ]
