# Generated by Django 3.2.5 on 2021-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_students'),
        ('students', '0003_auto_20210728_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.Course'),
        ),
    ]
