# Generated by Django 3.2.5 on 2021-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
