# Generated by Django 3.2.5 on 2021-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210728_0418'),
        ('courses', '0002_auto_20210727_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.Student'),
        ),
    ]
